export const PROTOCOL_VERSION = '0.5.0';

export * from './jsonrpc.js';
export * from './methods.js';
export * from './behavior-parser.js';
export * from './persona-prompt-template.js';
export * from './state.js';
export * from './schemas.js';
export * from './character-manifest.js';
export * from './provider-config.js';
export * from './provider-templates.js';
export * from './provider-migrate.js';
export * from './config-metadata.js';
export * from './mcp-config.js';
export * from './im-config.js';
export * from './kb-config.js';
export * from './memory-config.js';
export * from './persona-config.js';
export * from './trace-config.js';
export * from './prefs.js';
export * from './hotkeys.js';
export * from './interaction-cues.js';
export * from './plugin-config.js';
export * from './voice-config.js';
export * from './update-config.js';
export * from './macros.js';
export * from './lorebook.js';
